### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by jobwat** [davidmnoriega/boot2docker-sysdig#1]
Hi, first: thanks for sharing your work!

I wanted to enjoy csysdig as well on my docker machine on my mac, I first ran your Dockerfile using version 0.3.0 of sysdig but no luck

```
root@b2d-sysdig:~# sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

Any idea how to circumvent that one ?

Then I took your latest release: `v0.1.103`
The command `sysdig` works but return a screaming stream of events.. looking like this

```
docker@b2d:~$ sysdig | head
13 07:09:53.852615875 4 sysdig (2749) > switch next=0 pgft_maj=0 pgft_min=343 vm_size=150420 vm_rss=4196 vm_swap=0
14 07:09:53.852736562 0 <NA> (0) > switch next=7 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0
15 07:09:53.852745477 0 <NA> (7) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0
```

And I got no idea how to deal with it :|

`csysdig` returns an error:

```
docker@b2d:~$ csysdig
Error opening terminal: xterm-256color.
```

Any clue?

**Comment by davidmnoriega** [comment]
heh I've fallen asleep at the wheel. I'll work on updating for the latest release, but I have a question about your last part.

On your Mac, run `env | grep TERM`, then compare to what you see inside boot2docker. What happens when you set it to just `xterm`?

**Comment by davidmnoriega** [comment]
Figured out the terminal error. On Mac, the default value for `TERM` is `xterm-256color` but this does not exist in the VM(or linux?). Or it just goes by the name `xterm-color`, I think. The reason why I didn't see this was I had long since dealt with this issue by setting `TERM` to just `xterm` in my bash profile.

**Comment by jobwat** [comment]
Awesome, thanks, quick and efficient, a pleasurable answer :)
